language: java
jdk: 
- oraclejdk8

notifications: 
  email: 
    recipients: 
    - manuel.schoenlaub@gmail.com
    
    on_success: change
    on_failure: always

branches:
  only:
  - master
  - 3.0.x

env:
  global:
    - MONGO_REPO="http://repo.mongodb.org/apt/ubuntu"
    - REPO_TYPE="precise/mongodb-org/3.0 multiverse"
    - SOURCES_LOC="/etc/apt/sources.list.d/mongodb-org-3.0.list"
    - KEY_SERVER="hkp://keyserver.ubuntu.com:80"
    - MONGOD_PARAMS="--setParameter=enableTestCommands=1"
    - MONGOD_OPTS="--dbpath ./data --fork --logpath mongod.log ${MONGOD_PARAMS}"
    - TERM=dumb

before_install:
    # MongoDB Enterprise Edition 2.6
    - sudo apt-key adv --keyserver ${KEY_SERVER} --recv 7F0CEB10
    - echo "deb ${MONGO_REPO} ${REPO_TYPE}" | sudo tee ${SOURCES_LOC}

    # Update all the repositories
    - sudo apt-get update -qq

install:
    # Install MongoDB
    - sudo apt-get install mongodb-org
    - sudo stop mongod
    - mkdir data

before_script:
    - mongod ${MONGOD_OPTS}

script:
  - ./gradlew -q assemble
  - ./gradlew check -i -S -Pquicktest=true
